job_name: terminus-2__gpt-5.1-reasoning-high
jobs_dir: jobs
n_attempts: 5
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 16
  quiet: false
  retry:
    max_retries: 3
    exclude_exceptions:
      - BadRequestError
      - RateLimitError
      - AgentTimeoutError
      - VerifierTimeoutError
      - RewardFileNotFoundError
    wait_multiplier: 1.0
    min_wait_sec: 1.0
    max_wait_sec: 60.0
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: terminus-2
    model_name: openai/gpt-5.1
    kwargs:
      reasoning_effort: high
datasets:
  - registry:
      name: harbor
      url: https://raw.githubusercontent.com/laude-institute/harbor/main/registry.json
    name: terminal-bench
    version: "2.0"
