job_name: proprietary
jobs_dir: jobs
n_attempts: 5
timeout_multiplier: 1.0
orchestrator:
  type: local
  n_concurrent_trials: 64
  quiet: false
  retry:
    max_retries: 3
    exclude_exceptions:
      - BadRequestError
      - RateLimitError
      - AgentTimeoutError
      - VerifierTimeoutError
    wait_multiplier: 1.0
    min_wait_sec: 1.0
    max_wait_sec: 60.0
environment:
  type: daytona
  force_build: false
  delete: true
agents:
  - name: claude-code
    model_name: anthropic/claude-sonnet-4-5-20250929
    kwargs:
      version: "2.0.31"
  - name: claude-code
    model_name: anthropic/claude-opus-4-1-20250805
    kwargs:
      version: "2.0.31"
  - name: claude-code
    model_name: anthropic/claude-haiku-4-5-20251001
    kwargs:
      version: "2.0.31"
  - name: codex
    model_name: openai/gpt-5-codex
    kwargs:
      version: "0.53.0"
  - name: codex
    model_name: openai/gpt-5
    kwargs:
      version: "0.53.0"
  - name: codex
    model_name: openai/gpt-5-mini
    kwargs:
      version: "0.53.0"
  - name: codex
    model_name: openai/gpt-5-nano
    kwargs:
      version: "0.53.0"
  - name: gemini-cli
    model_name: gemini/gemini-2.5-pro
    kwargs:
      version: "0.11.3"
  - name: gemini-cli
    model_name: gemini/gemini-2.5-flash
    kwargs:
      version: "0.11.3"
datasets:
  - registry:
      name: harbor
      url: https://raw.githubusercontent.com/laude-institute/harbor/main/registry.json
    name: terminal-bench
    version: "2.0"
